"""M3U playlist export — importable into Serato, rekordbox, Traktor, VirtualDJ.

Generates extended M3U playlists (.m3u8) with metadata comments that
DJ software can read. This is the bridge between finding tracks and
actually loading them into your DJ crates.

Two modes:
1. URL-based: Points to track URLs (for streaming/preview playlists)
2. Local-file: Points to local paths after download (for real DJ use)
"""

from __future__ import annotations

from pathlib import Path

from freetracks.core.models import Track, SearchResults


def export_m3u(
    results: SearchResults,
    output_path: str | Path,
    local_music_dir: str | Path | None = None,
) -> Path:
    """Export search results as an extended M3U playlist.

    If local_music_dir is provided, generates paths assuming tracks are
    downloaded there as: {local_music_dir}/{artist} - {title}.{ext}

    Otherwise, uses track URLs for streaming-capable players.

    Args:
        results: SearchResults containing tracks.
        output_path: Output .m3u or .m3u8 file path.
        local_music_dir: Optional local directory path for downloaded files.

    Returns:
        Path to the written file.
    """
    path = Path(output_path)
    lines = ["#EXTM3U", ""]

    # Add metadata comment
    lines.append(f"# Generated by Free Track Finder")
    lines.append(f"# Query: {results.query}")
    lines.append(f"# Tracks: {results.track_count}")
    lines.append("")

    for track in results.tracks:
        # Extended info line: #EXTINF:duration,Artist - Title
        duration = int(track.duration_seconds) if track.duration_seconds else -1
        lines.append(f"#EXTINF:{duration},{track.artist} - {track.title}")

        # Extra metadata as comments (some players read these)
        if track.bpm:
            lines.append(f"#EXTBPM:{track.bpm:.0f}")
        if track.key:
            lines.append(f"#EXTKEY:{track.key}")
        if track.genre:
            lines.append(f"#EXTGENRE:{track.genre}")

        # File path or URL
        if local_music_dir:
            local_dir = Path(local_music_dir)
            # Sanitize filename
            safe_artist = _sanitize_filename(track.artist)
            safe_title = _sanitize_filename(track.title)
            ext = track.file_format.value if track.file_format.value != "unknown" else "mp3"
            local_path = local_dir / f"{safe_artist} - {safe_title}.{ext}"
            lines.append(str(local_path))
        else:
            lines.append(track.download_url or track.url)

        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return path


def export_m3u_string(
    results: SearchResults,
    local_music_dir: str | Path | None = None,
) -> str:
    """Export as M3U string for stdout."""
    lines = ["#EXTM3U", ""]

    for track in results.tracks:
        duration = int(track.duration_seconds) if track.duration_seconds else -1
        lines.append(f"#EXTINF:{duration},{track.artist} - {track.title}")
        if track.bpm:
            lines.append(f"#EXTBPM:{track.bpm:.0f}")
        if track.key:
            lines.append(f"#EXTKEY:{track.key}")

        if local_music_dir:
            local_dir = Path(local_music_dir)
            safe_artist = _sanitize_filename(track.artist)
            safe_title = _sanitize_filename(track.title)
            ext = track.file_format.value if track.file_format.value != "unknown" else "mp3"
            lines.append(str(local_dir / f"{safe_artist} - {safe_title}.{ext}"))
        else:
            lines.append(track.download_url or track.url)

        lines.append("")

    return "\n".join(lines)


def _sanitize_filename(name: str) -> str:
    """Remove characters that are invalid in filenames."""
    invalid_chars = '<>:"/\\|?*'
    result = name
    for char in invalid_chars:
        result = result.replace(char, "")
    # Collapse multiple spaces
    result = " ".join(result.split())
    return result.strip()
